site_name: Vos Données, Votre Contrôle
site_url: https://www.thouvenin.eu/blog
repo_url: https://github.com/gthvn1/blog
repo_name: github.com/gthvn1/blog
plugins:
  - search
  - tags
  - blog:
      blog_toc: true
theme:
  name: material
  features:
    - navigation.indexes
    - toc.follow
    - toc.integrate
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: about.md
