site_name: Vos Données, Votre Contrôle
site_url: https://www.thouvenin.eu/blog
repo_url: https://github.com/gthvn1/blog
repo_name: github.com/gthvn1/blog
plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog:
      blog_toc: true
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.indexes
    - toc.follow
    - toc.integrate
nav:
  - Home: index.md
  - Definition: definition.md
  - Blog:
    - blog/index.md
    - tags.md
  - Liens: liens.md
